project:
  type: website
  output-dir: docs
  pre-render: "python3 gerar_posts_json.py"

lang: pt-BR

website:
  title: "Blog do Marcellini"
  favicon: images/banner.jpeg
  site-url: https://blogdomarcellini.com.br

  navbar:
    left:
      - href: index.qmd
        text: Início
      - text: "🧭 Explorar"
        menu:
          - text: "🏷️ Tags"
            href: tags.qmd
          - text: "📂 Categorias"
            href: categories.qmd
      - text: "🧠 Ciências Exatas"
        menu:
          - text: "🧮 Matemática"
            href: posts/matematica/index.qmd
          - text: "📊 Estatística"
            href: posts/estatistica/index.qmd
          - text: "🔭 Física"
            href: posts/fisica/index.qmd
          - text: "💻 Programação"
            href: posts/programacao/index.qmd
          - text: "🤖 Inteligência Artificial"
            href: posts/programacao/ia/index.qmd
      - text: "📝 Blog Pessoal"
        menu:
          - text: "📝 Blog Pessoal"
            href: posts/pessoal/index.qmd
          - text: "👤 Sobre Mim e Sobre o Blog"
            href: posts/pessoal/sobre-o-blog.qmd
      - text: "📘 Cursos"
        menu:
          - text: "🧮 Cursos de Matemática"
            href: posts/cursos/matematica/index.qmd
          - text: "📊 Cursos de Estatística"
            href: posts/cursos/estatistica/index.qmd
      - href: guia.qmd
        text: "🗺️ Mapa do Site"
    right:
      - text: "EN 🇬🇧"
        href: "https://marcellini-celso.github.io/blog-marcellini-en/"
        target: _blank
        rel: noopener
      - icon: envelope
        text: "Contato"
        href: "mailto:prof.marcellini@gmail.com" 

  page-footer:
    left: "© 2025 - Blog do Marcellini"
    right: >
      📬 [Contato por E-mail](mailto:prof.marcellini@gmail.com)<br>
      💻 <a href="https://github.com/marcellini-celso/blog-marcellini-pt.git" target="_blank">GitHub do Projeto</a>

format:
  html:
    theme: cosmo
    css: 
      - styles.css
      - assets/css/custom.css
      - assets/css/cards.css
      - assets/css/chips.css
    toc: true
    toc-title: "Nesta página"
    highlight-style: github
    open-graph: true
    twitter-card: true
    image: images/banner.png
    include-in-header: 
      - "analytics.html"
      - text: |
          <link rel="alternate" hreflang="en"
                href="https://en.blogdomarcellini.com.br/" />
          <link rel="alternate" hreflang="x-default"
                href="https://blogdomarcellini.com.br/" />
    include-after-body:
      - assets/js/enhance-categories.js

search: true

publish:
  provider: gh-pages
  domain: blogdomarcellini.com.br
  
filters:
  - naquiz

resources:
  - robots.txt
  - posts.json
  - images/**

from: markdown+tex_math_dollars+tex_math_single_backslash

