---
title: "artigo"
format: html
---

[⬅ Voltar para Todas as Tags](../tags.qmd)

## Posts com a tag **artigo**

- [📘 🛰️ Relatividade Especial: Einstein, o Tempo e a Velocidade da Luz](/posts/fisica/relatividade-especial.html)
- [📘 🧬 100 Anos da Mecânica Quântica (1925–2025)](/posts/fisica/100-anos-mecanica-quantica.html)
- [📘 👨‍💻 📄 📊 Modelos de Código em R para Usar com Quarto](/posts/programacao/r/modelos-r-quarto.html)
- [📘 👨‍💻 📄 🐍 Modelos de Código em Python para Usar com Quarto](/posts/programacao/python/modelos-python-quarto.html)
- [📘 👨‍💻 📄 Modelo de Markdown com Quarto -- Parte 1](/posts/programacao/quarto/modelos-markdown.html)
- [📘 👨‍💻 📄 Modelos de index.qmd para Projetos Quarto](/posts/programacao/quarto/modelos-index-quarto.html)
- [📘 👨‍💻 📄 Modelo de Markdown com Quarto -- Parte 2](/posts/programacao/quarto/outros-modelos-markdown.html)
- [📘 👨‍💻 📄 Modelos de Quarto Markdown — Guia Completo](/posts/programacao/quarto/modelos-quarto-markdown.html)
- [📘 👨‍💻 📄 YAML no Quarto: O Coração Invisível dos Seus Documentos](/posts/programacao/quarto/yaml-no-quarto.html)
- [📘 👨‍💻 📐 Modelos de LaTeX para Usar com Quarto](/posts/programacao/latex/modelos-latex-quarto.html)
- [📘 ✨ 🧮 ⚛️ Fórmulas que Marcaram a História](/posts/matematica/equacoes-historicas.html)
- [📘 🧮 A Beleza é o Primeiro Teste — G. H. Hardy e a Matemática como Arte](/posts/matematica/beleza-matematica.html)
- [📘 🧮 Por que 0! = 1?](/posts/matematica/fatorial-zero.html)
